---
title: Hello R Markdown
subtitle: Output Formats
author: "Horacio"
date: "13-01-2023"
output:
  html_document:
    theme: !expr sample(c("yeti", "united", "lumen"), 1)
---

Esta es una línea con una palabra en *itálica*.

Esta es una línea con una palabra en **negrita**.

H~3~PO~4~

Esta es una línea con código *inline* `installed.packages()`

Este es un vínculo: [RStudio](https://posit.co)

Esta es una [^1]

[^1]: Nota al pie.

# Encabezado primer nivel

## Encabezado segundo nivel

### Encabezado tercer nivel

# Prefacio {-}

- Un ítem
- Un ítem
- Un ítem
  - Un ítem más
  - Un ítem más
  - Un ítem más
    - Otro ítem más


> "I thoroughly disapprove of duels. If a man should challenge me,
  I would take him kindly and forgivingly by the hand and lead him
  to a quiet place and kill him."
>
> --- Mark Twain

> "I thoroughly disapprove of duels. If a man should challenge me,
  I would take him kindly and forgivingly by the hand and lead him
  to a quiet place and kill him."
>
> --- Mark Twain

```
This text is displayed verbatim / preformatted
```

    This text is displayed verbatim / preformatted
    
In R, the character
# indicates a comment.

The result of 5
- 3 is 2.

$f(k) = {n \choose k} p^{k} (1-p)^{n-k}$



